controller_joint_names: ['', 'rueda_izquierda_joint', 'rueda_derecha_joint', 'apoyo_izquierdo_delantero_joint', 'apoyo_izquierdo_trasero_joint', 'apoyo_derecho_delantero_joint', 'apoyo_derecho_trasero_joint', ]
